### PR TITLE
Fix tree-view horizontal scroll by removing extra overflow: hidden

### LINKED ISSUE #3: File navigator window has no horizontal scroll
Thank you for an awesome theme!

Feature request: horizontal scroll bars in the file navigator window. 

Context: It's impossible to navigate projects with a deep directory structure unless I expand the file navigator window. It does produce scroll bars when I make the file navigator window very narrow, however it does not scroll enough to see all the files. I've attached a screenshot below that demonstrates my issue: 

screen shot 2017-11-04 at 6 34 35 pm

A lot of Atom themes allow me to scroll the file navigator window horizontally to see all the files/folders in a project without adjusting the width of the window. I think it would be awesome to include this functionality in an awesome theme! 😄 

Thank you!

### PR DESCRIPTION
**Pull request by paradoxxxzero**
This fixes #3

### CODE REVIEW

**Comment by noudadrichem** [comment]
Hi @paradoxxxzero ,

Thank you for your PR, have you checked this out with git status and selected files? 
When I tried this it starting to bug those 2.

Sincerely

**Comment by paradoxxxzero** [comment]
You are right, it bugs on horizontal scroll.
I investigated a bit more and letting the `tree-view-root` `min-width` at `min-content` (Removing this line: https://github.com/Yummygum/city-lights-ui-atom/blob/master/styles/tree-view.less#L21) fixes the scroll but the git indicator is logically positioned at the right end of the panel and thus hidden by the scroll.

I have no idea how to have both the git indicator always visible at the right side and a horizontal scroll.
Sorry!

**Comment by noudadrichem** [comment]
This is the same issue I stumbled on, thank you for your help! I'll investigate this more!

**Comment by jedwards1211** [comment]
@noudadrichem When I discovered this fix independently in the dev tools itself, it didn't push the status icons over beyond the right of the scroll pane.  It causes the ugly layout issue pictured below but this is very preferable to not being able to scroll horizontally.
Have you considered moving the status icons to the left side of the tree view instead?
The right side would work fine if the icons could stick to the right side regardless of the horizontal scroll position, but it would be impossible to get this ideal behavior with pure CSS.
Icons on the right side of any tree view are just prone to layout issues:
image

**Pull request closed without merging**
